project:
  type: website

website:
  title: "G2T4: From Coast to City"
  navbar:
    left: 
      - href: overview.html
        text: Project Overview
      - href: documentation.qmd
        text: Methodology
      - href: poster.qmd
        text: Poster
      - href: findings.qmd
        text: Project Analysis
      - href: report.qmd
        text: Report
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

