project:
  type: website

website:
  title: "GISProject"
  navbar:
    left: 
      - href: overview.html
        text: Overview
      - href: methodology.gmd
        text: Methodology
      - href: maps.qmd
        text: Analysis
      - href: findings.qmd
        text: Report
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

